---
kind: pipeline
type: kubernetes
name: taskd (pull request)

trigger:
    event:
        - pull_request
    repo:
        - helm-charts/taskd

steps:
    - name: build docker image
      image: plugins/docker
      settings:
          dry_run: true
          repo: shadow53/taskd
    - name: lint helm chart
      image: shadow53/helm-netlify
      settings:
          helm_rebuild_repo: false
          helm_package: true
          helm_lint: true

---
kind: pipeline
type: kubernetes
name: taskd docker (develop)

trigger:
    branch:
        - master
    repo:
        - helm-charts/taskd

steps:
    - name: build/publish docker image
      image: plugins/docker
      settings:
          repo: shadow53/taskd
          username: shadow53
          password:
              from_secret: docker_token
    - name: lint helm chart
      image: shadow53/helm-netlify
      settings:
          helm_git_beta: true
          helm_rebuild_repo: true
          helm_package: true
          helm_lint: true
          netlify_auth_token:
              from_secret: netlify_auth_token
          netlify_account_slug: Shadow53
          netlify_create_site: true
          netlify_site_name: "Shadow53 Helm Beta Charts"
          netlify_disable_telemetry: true
          repo_root_url: https://charts-beta.shadow53.com
          repo_path: /drone/src/taskd
          append_helm_repo: true
          keep_versions: 3

---
kind: pipeline
type: kubernetes
name: taskd docker (tag)

trigger:
    event:
        - tag
    repo:
        - helm-charts/taskd

steps:
    - name: build/publish docker image
      image: plugins/docker
      settings:
          auto_tag: true
          repo: shadow53/taskd
          username: shadow53
          password:
              from_secret: docker_token
          tags:
              - latest
    - name: publish helm chart
      image: shadow53/helm-netlify
      settings:
          helm_rebuild_repo: true
          helm_package: true
          helm_lint: true
          netlify_auth_token:
              from_secret: netlify_auth_token
          netlify_account_slug: Shadow53
          netlify_create_site: true
          netlify_site_name: "Shadow53 Helm Charts"
          netlify_disable_telemetry: true
          repo_root_url: https://charts.shadow53.com
          repo_path: /drone/src/taskd
          append_helm_repo: true
          keep_versions: 5
