---
kind: pipeline
type: kubernetes
name: taskd docker (pull)

trigger:
    event:
        - pull_request
    repo:
        - helm-charts/taskd

steps:
    - name: build/publish docker image
      image: plugins/docker
      settings:
          dry_run: true
          dockerfile: docker/Dockerfile
          repo: shadow53/taskd

---
kind: pipeline
type: kubernetes
name: taskd docker (develop)

trigger:
    branch:
        - master
    repo:
        - helm-charts/taskd

steps:
    - name: build/publish docker image
      image: plugins/docker
      settings:
          dockerfile: docker/Dockerfile
          repo: shadow53/taskd
          username: shadow53
          password:
              from_secret: docker_token
          tags: develop

---
kind: pipeline
type: kubernetes
name: taskd docker (tag)

trigger:
    event:
        - tag
    repo:
        - helm-charts/taskd

steps:
    - name: build/publish docker image
      image: plugins/docker
      settings:
          auto_tag: true
          dockerfile: docker/Dockerfile
          repo: shadow53/taskd
          username: shadow53
          password:
              from_secret: docker_token
          tags:
              - latest
