---
kind: pipeline
type: kubernetes
name: taskd (pull request)

trigger:
    event:
        - pull_request
    repo:
        - helm-charts/taskd

steps:
    - name: build docker image
      image: plugins/docker
      settings:
          dry_run: true
          repo: shadow53/taskd
    - name: lint helm chart
      image: alpine/helm:3.4.2
      commands:
          - helm lint --strict /drone/src/taskd/

---
kind: pipeline
type: kubernetes
name: taskd docker (develop)

trigger:
    branch:
        - master
    repo:
        - helm-charts/taskd

steps:
    - name: build/publish docker image
      image: plugins/docker
      settings:
          repo: shadow53/taskd
          username: shadow53
          password:
              from_secret: docker_token
          tags: develop

---
kind: pipeline
type: kubernetes
name: taskd docker (tag)

trigger:
    event:
        - tag
    repo:
        - helm-charts/taskd

steps:
    - name: build/publish docker image
      image: plugins/docker
      settings:
          auto_tag: true
          repo: shadow53/taskd
          username: shadow53
          password:
              from_secret: docker_token
          tags:
              - latest
